name: kore_farms
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-265.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  backendless_sdk: ^7.2.3
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - images/



fonts:
    - family: Yellowtail
      fonts:
        - asset: fonts/Yellowtail-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
